apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubedriftguard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedriftguard.labels" . | nindent 4 }}
